version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  gin_server:
    build:
      context: .
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - /app/tmp  # A tmp folder to handle any temporary files
    ports:
      - "8080:8080"
      - "4000:4000"  # Port for delve
    command: [ "dlv", "debug", "--headless", "--accept-multiclient", "--api-version=2", "--listen=:4000", "--continue" ]
    depends_on:
      - mongodb

volumes:
  mongo_data: